---
name: laathi
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <=3.1.2'
dependencies:
  flutter:
    sdk: flutter
  animated_toggle_switch: ^0.7.0
  uuid: ^3.0.7
  geolocator: ^9.0.2
  geocoding: ^2.0.4
  cupertino_icons: ^1.0.2
  sizer: ^2.0.15
  flutter_svg: ^2.0.5

  rxdart: ^0.27.7
  shared_preferences: ^2.1.2
  flare_flutter: ^3.0.2
  flutter_local_notifications: ^15.1.0+1
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.7.0
  flutter_riverpod: ^2.3.6
  country_picker: ^2.0.20
  url_launcher: ^6.1.11
  permission_handler: ^10.2.0
  flutter_sms_inbox: ^1.0.3
  otp_timer_button: ^1.1.0
  scrollable_positioned_list: ^0.3.8
  ensure_visible_when_focused: ^1.1.1
  emoji_keyboard_flutter: ^1.3.1
  flutter_linkify: ^6.0.0
  image_picker: ^1.0.0
  audioplayers: ^4.1.0
  google_fonts: ^4.0.1
  path_provider: ^2.0.15
  flutter_sound: ^9.2.13
  record: ^4.4.4
  firebase_storage: ^11.2.4
  change_app_package_name: ^1.1.0

  contacts_service: ^0.6.2




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/