// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjOUPlIzTsz2m8ZU5YY_2APr5U7Yg6mMs',
    appId: '1:41144261320:web:97cb83a2737cbd4cfd23fd',
    messagingSenderId: '41144261320',
    projectId: 'laathi-app',
    authDomain: 'laathi-app.firebaseapp.com',
    databaseURL: 'https://laathi-app-default-rtdb.firebaseio.com',
    storageBucket: 'laathi-app.appspot.com',
    measurementId: 'G-VF6JMGY391',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH6hUJKMFkmCIY-IMHXFJmTko2zRusyOo',
    appId: '1:41144261320:android:deb2bef45e32bd10fd23fd',
    messagingSenderId: '41144261320',
    projectId: 'laathi-app',
    databaseURL: 'https://laathi-app-default-rtdb.firebaseio.com',
    storageBucket: 'laathi-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArkKUHeC3lcnGRgSH3wKd-U0kQpDBw_2o',
    appId: '1:41144261320:ios:e9f1efb13bd0eb9cfd23fd',
    messagingSenderId: '41144261320',
    projectId: 'laathi-app',
    databaseURL: 'https://laathi-app-default-rtdb.firebaseio.com',
    storageBucket: 'laathi-app.appspot.com',
    androidClientId: '41144261320-eil133khdtp2mmba2q9l64t1ce102j0m.apps.googleusercontent.com',
    iosClientId: '41144261320-fv8okkk1qgir316obv1gmn9jn4mpo17c.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArkKUHeC3lcnGRgSH3wKd-U0kQpDBw_2o',
    appId: '1:41144261320:ios:e9f1efb13bd0eb9cfd23fd',
    messagingSenderId: '41144261320',
    projectId: 'laathi-app',
    databaseURL: 'https://laathi-app-default-rtdb.firebaseio.com',
    storageBucket: 'laathi-app.appspot.com',
    androidClientId: '41144261320-eil133khdtp2mmba2q9l64t1ce102j0m.apps.googleusercontent.com',
    iosClientId: '41144261320-fv8okkk1qgir316obv1gmn9jn4mpo17c.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
